# Dockerfile.frontend
FROM node:18

# Establece directorio de trabajo
WORKDIR /app

# Copia solo los archivos necesarios del frontend
COPY frontend/package*.json ./
COPY frontend/ ./

# Instala dependencias (omit=optional evita errores con @rollup)
RUN npm install --legacy-peer-deps --omit=optional

# Exponer el puerto de Vite
EXPOSE 5173

# Corre el servidor de desarrollo
CMD ["npm", "run", "dev"]
