FROM node:18

WORKDIR /app

COPY . /app

# Eliminar posibles residuos
RUN rm -rf node_modules package-lock.json

# Instalar ignorando dependencias opcionales de Rollup
RUN npm install --legacy-peer-deps --omit=optional

CMD ["npm", "run", "dev"]
