# Dockerfile.backend
FROM python:3.10-slim
WORKDIR /app
COPY backend /app
RUN apt-get update && apt-get install -y portaudio19-dev ffmpeg && \
    pip install --no-cache-dir -r requirements.txt
CMD ["python", "app.py"]